feat: prevent action from running on master branch

diff --git a/.github/workflows/update-dependencies.yml b/.github/workflows/update-dependencies.yml
--- a/.github/workflows/update-dependencies.yml
+++ b/.github/workflows/update-dependencies.yml
@@ -17,6 +17,12 @@ jobs:
         with:
           ref: ${{ github.event.inputs.branch }}
 
+      - name: Check if branch is master
+        if: ${{ github.event.inputs.branch == 'master' }}
+        run: |
+          echo "Cannot run on master branch"
+          exit 1
+
       - name: Set up Ruby
         uses: ruby/setup-ruby@v1
         with:
